import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Kivo",
  description: "The terms that govern your use of Kivo.",
};

// NOTE: Drafted for launch; have legal counsel review before scaling paid
// acquisition (especially recording-consent and liability language).
export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-20 text-[15px] leading-relaxed">
      <h1 className="mb-2 text-3xl font-bold">Terms of Service</h1>
      <p className="mb-10 text-sm opacity-70">Effective: July 2, 2026</p>

      <Section title="1. Agreement">
        <p>
          By creating an account or using Kivo you agree to these Terms and to
          our <Link className="underline" href="/privacy">Privacy Policy</Link>.
          If you don&apos;t agree, don&apos;t use the service.
        </p>
      </Section>

      <Section title="2. The service">
        <p>
          Kivo transcribes live conversations captured by your device&apos;s
          microphone and provides AI-generated answers, summaries, and related
          features. Features and plan limits may change as the product evolves.
        </p>
      </Section>

      <Section title="3. Recording responsibility">
        <p>
          You are solely responsible for complying with all laws that apply to
          recording or transcribing conversations where you use Kivo, including
          obtaining consent from every participant where required. You agree not
          to use Kivo to transcribe anyone secretly or without any legally
          required consent, and you accept full responsibility for any claim
          arising from your failure to do so.
        </p>
      </Section>

      <Section title="4. Your account">
        <p>
          Keep your credentials secure; you&apos;re responsible for activity under
          your account. You must be at least 16 years old.
        </p>
      </Section>

      <Section title="5. Acceptable use">
        <p>
          Don&apos;t abuse the service: no unlawful surveillance, harassment,
          attempts to break or overload the system, resale of the service,
          scraping, or circumvention of plan limits. We may suspend or terminate
          accounts that violate these Terms.
        </p>
      </Section>

      <Section title="6. Subscriptions and billing">
        <p>
          Paid plans bill monthly through Stripe and renew automatically until
          canceled. You can cancel anytime from Settings → Manage billing;
          access continues to the end of the paid period. Plan limits (listening
          hours, history retention, and similar) are described on the pricing
          page. Fees are non-refundable except where required by law.
        </p>
      </Section>

      <Section title="7. Your content">
        <p>
          You own your transcripts, questions, uploaded files, and other content.
          You grant us the limited license needed to operate the service —
          storing, processing, and transmitting your content to the service
          providers listed in the Privacy Policy. We don&apos;t use your content to
          train AI models.
        </p>
      </Section>

      <Section title="8. AI output disclaimer">
        <p>
          Kivo&apos;s answers are generated by AI and can be wrong, incomplete, or
          misattribute who said what. They are not legal, medical, financial, or
          other professional advice. Verify anything that matters before acting
          on it.
        </p>
      </Section>

      <Section title="9. Disclaimers and liability">
        <p>
          The service is provided &quot;as is&quot; without warranties of any kind. To
          the maximum extent permitted by law, our total liability for any claim
          arising from the service is limited to the amount you paid us in the
          twelve months before the claim, and we are not liable for indirect,
          incidental, or consequential damages.
        </p>
      </Section>

      <Section title="10. Termination">
        <p>
          You can delete your account at any time in Settings, which permanently
          removes your data as described in the Privacy Policy. We may suspend
          or terminate the service for breach of these Terms.
        </p>
      </Section>

      <Section title="11. Changes">
        <p>
          We may update these Terms; material changes will be announced in the
          app. Continued use after changes take effect constitutes acceptance.
        </p>
      </Section>

      <Section title="12. Contact">
        <p>
          <a className="underline" href="mailto:hello@kivo.ai">hello@kivo.ai</a>
        </p>
      </Section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-3 text-xl font-semibold">{title}</h2>
      {children}
    </section>
  );
}
